FROM postgres:18

RUN mkdir -p /docker-entrypoint-initdb.d
RUN chmod -R 755 /docker-entrypoint-initdb.d
EXPOSE 5432
HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=3 \
  CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1
