FROM redis:8.2.2

RUN mkdir -p /usr/local/etc/redis
RUN mkdir -p /data && chown redis:redis /data
USER redis
EXPOSE 6379
HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=3 \
  CMD redis-cli ping || exit 1
CMD ["redis-server"]
